### ISSUE TITLE
problem with -F option

### ISSUE THREAD

**Issue by jachymb** [PatrickTrentin88/gltl2ba#1]
Hello, when I use `gltl2ba -gF ltl.txt`, I get the following error: `/usr/bin/gltl2ba: expected str, bytes or os.PathLike object, not _io.TextIOWrapper`

There is a workaround: ```gltl2ba -gf "`cat ltl.txt`"```

**Comment by PatrickTrentin88** [comment]
Thank you for the bug report, the issue should now be fixed.
